# Traefik 2 (2.0.7) config file.

# Enables accesslog
[accessLog]

# Providers (platform which traefik will connect with).
[providers]
  [providers.docker]
    exposedByDefault = false # Disable automatic rules for running containers. Used to avoid un-used rules, you can enable it if youre curious tho.
    endpoint = "unix:///var/run/docker.sock" # links the docker socket to traefik. Used to allow traefik to manage docker.

 
# Entrypoints (exposed ports that traefik will listen to trough tcp)
[entryPoints]
  [entryPoints.web]
    address = ":80"

  [entryPoints.websecure]
    address = ":443"

# Api (api and traefik's dashboard (automatically exposed on port 8080))
[api]
  insecure = true
  dashboard = true

# Acme (ACME config with the basic le (Lets Encrypt) config, domains will be specified on each container via labels, or here.
[certificatesresolvers.le.acme]
  email = "youremail@mailprovider.com"
  storage = "acme.json" # Path where our acme file will be generated, in this case "./acme.json".
  tlschallenge = "true"

    [certificatesresolvers.le.acme.httpChallenge]
    entryPoint = "web"
    
    # dnsChallege is not mandatory but it can be used for wildcard certificates.
    [certificatesResolvers.le.acme.dnsChallenge]
    provider = "digitalocean"
    delayBeforeCheck = 5
